#! /bin/sh
# Debconf config file for fcron
# $Id: config,v 1.1 2004-01-29 10:31:56 thib Exp $

set -e
. /usr/share/debconf/confmodule

# Babysit users who don't read README.Debian
db_title fcron
db_input high fcron/anacronwarn || true
db_go

exit 0
