#!/bin/sh
# Uninstall fcron under SysV system.
#

# $Id: boot-uninstall,v 1.3 2000-09-18 08:24:51 thib Exp $

PATH="/sbin:/usr/sbin:/bin:/usr/bin:/usr/X11R6/bin"

ROOTDIR=""
if test -d /etc/rc.d/init.d/; then
    ROOTDIR="/etc/rc.d"
elif test -d /etc/init.d/; then
    ROOTDIR="/etc"
fi
if test $ROOTDIR != ""; then
    rm -f $ROOTDIR/init.d/fcron-debug
    rm -f $ROOTDIR/init.d/fcron

    rm -f $ROOTDIR/rc2.d/S40fcron
    rm -f $ROOTDIR/rc3.d/S40fcron
    rm -f $ROOTDIR/rc4.d/S40fcron
    rm -f $ROOTDIR/rc5.d/S40fcron

    rm -f $ROOTDIR/rc0.d/K60fcron
    rm -f $ROOTDIR/rc6.d/K60fcron
else
    echo "You may delete fcron from your rc.local manually"
fi
