#!/bin/sh
# Uninstall fcron under SysV system.
#

# $Id: boot-uninstall,v 1.6 2001-03-02 17:48:34 thib Exp $

PATH="/sbin:/usr/sbin:/bin:/usr/bin:/usr/X11R6/bin"

if test `uname -s` = "FreeBSD"; then
  rm -f /usr/local/etc/rc.d/fcron.sh
else
  ROOTDIR=""
  if test -f /etc/rc.d/init.d/fcron; then
    ROOTDIR="/etc/rc.d"
  elif test -f /etc/init.d/fcron; then
    ROOTDIR="/etc"
  fi
  if test $ROOTDIR != ""; then
    rm -f $ROOTDIR/init.d/fcron

    rm -f $ROOTDIR/rc2.d/S40fcron
    rm -f $ROOTDIR/rc3.d/S40fcron
    rm -f $ROOTDIR/rc4.d/S40fcron
    rm -f $ROOTDIR/rc5.d/S40fcron

    rm -f $ROOTDIR/rc0.d/K60fcron
    rm -f $ROOTDIR/rc6.d/K60fcron
  else
    echo
    echo "You should delete fcron from your boot script manually"
    echo
  fi
fi

