#!/bin/sh

# $Id: gen-doc,v 1.7 2000-06-22 15:33:14 thib Exp $

PREVIOUS=`cat ./VERSION`


if test $PREVIOUS != $1; then
    cd doc
    for i in [A-Z]*
    do
    if test $i != RCS; then
	echo $i
	sed -e "s:fcron version [0-9.]*:fcron version $1:" < $i > tmp
	mv -f tmp $i
	chown $USER $i
	rm -f tmp
    fi
    done    
fi


