#!/bin/sh

# $Id: gen-doc,v 1.4 2000-05-16 19:51:41 thib Exp $

if test $UID -eq 0; then
  su $USER
fi

PREVIOUS=`cat ./VERSION`


if test $PREVIOUS != $1; then
    cd doc
    for i in *
    do
    if test $i != RCS; then
	echo $i
	sed -e "s:fcron version .* :fcron version $1 :" < $i > tmp
	mv -f tmp $i
	rm -f tmp
    fi
    done    
fi


